version: '3.5'

networks:
  default:
    name: default-network

services:

    app:
      build: .
      image: local/app
      container_name: app
      restart: "no"
      volumes:
          - ".:/home/app"
          - ".:/app"

    web:
        image: nginx:latest
        container_name: web
        restart: always
        volumes:
            - "./config/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf"
            - ".:/app"
        ports:
            - "8000:80"
            - "3000:443"
        links:
            - php

    php:
       image: php:7-fpm
       container_name: php
       restart: always
       volumes:
           - ".:/app"

    composer:
       image: composer
       container_name: composer
       restart: "no"
       volumes:
           - ".:/app"
       command: install

    node:
       image: node:latest
       container_name: node
       restart: "no"
       working_dir: /home/node
       volumes:
          - ".:/home/node"
          - ".:/app"
       command: "npm install"
